### ISSUE TITLE
Turn does not get transferred to other players if current player gets the question wrong

### ISSUE THREAD

**Issue by lifeofchrome** [Sven65/TriviaPartyBugs#1]
**Describe the bug**
When playing a 2 player game, if someone gets the question wrong, they get another question selection and this happens until they get the question right instead of the next person in the list selecting a question.

**To Reproduce**
1. Get a question wrong in a 2+ player game.

**Expected behavior**
The next player in the list should get the orange border and be able to choose a question to answer.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome 67.0.3396.99

**Comment by Sven65** [comment]
This has been fixed.
