### ISSUE TITLE
Account registration popup closes automatically

### ISSUE THREAD

**Issue by lifeofchrome** [Sven65/TriviaPartyBugs#12]
**Describe the bug**
When clicking the register button, the register popup closes shortly after, so you misses the message about checking your email to verify your address.

**To Reproduce**
1. Create an account
2. When you click the register button, notice how the account creation popup closes automatically

**Expected behavior**
The popup should stay open and require you to click the X in the top right to close.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome 69.0.3489.0
 - TriviaParty Version: 0.2.13

**Additional context**
This should be further changed to avoid the tiny, easy-to-miss white text at the top of the register popup to first closing the register popup, then creating a new email verification popup telling the user that the verification email has been sent, or click OK to send it, or ask if they want it sent at all, or whatever else.

I'd also like to point out that the constant red banner at the top for unverified users could prove to be annoying. I'd suggest something along the lines of what (I think) Discord uses - a red banner across the top with an X button, when you click the X it says _why_ you should register your email, in their case to claim the account, and then never showing the banner again and putting a red box in the user profile popup thing. Maybe just an X button is best, I'm not sure.

**Comment by Sven65** [comment]
Done and fixed
