### ISSUE TITLE
Avatars do not show up in chat

### ISSUE THREAD

**Issue by lifeofchrome** [Sven65/TriviaPartyBugs#2]
**Describe the bug**
Instead of the avatar the user uploaded appearing to the left of their name in the chat area, a gray image with the text "128x128" is displayed instead.

**To Reproduce**
1. Upload an avatar
2. Join/create a game
3. Send a chat message

**Expected behavior**
Your uploaded avatar should show in the chat area.

**Screenshots**
![image](https://user-images.githubusercontent.com/8226943/42287898-fa474b7c-7f7d-11e8-8b66-aac7be8a6972.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome 67.0.3396.99
 - TriviaParty Version: 0.2.3

**Comment by Sven65** [comment]
Does it happen if you reload the page?
Does it happen if the user that changed their avatar reloads the page?

**Comment by lifeofchrome** [comment]
Yes, the issue persists upon reload.
I'm having issues changing my avatar (I upload an image, wait, doesn't work) so I can't test if it persists upon changing avatar and reloading but it seems like it would.

**Comment by Sven65** [comment]
Who does it persist for upon whos reload?

**Comment by Sven65** [comment]
Fixed.
