### ISSUE TITLE
Usernames displaying poorly in player list

### ISSUE THREAD

**Issue by lifeofchrome** [Sven65/TriviaPartyBugs#3]
**Describe the bug**
Usernames in the player list while a game is running display poorly. This includes being positioned too far up, right, and having a white color with a white background, and likely being too big in some cases.

**To Reproduce**
1. Look at the player list while playing a game.

**Expected behavior**
The username for each player should be centered under their avatar in a contrasting color and be scaled to fit the available space.

**Screenshots**
![image](https://user-images.githubusercontent.com/8226943/42288016-b0ef8204-7f7e-11e8-97e8-070ccf42a967.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome 67.0.3396.99
 - TriviaParty Version: 0.2.3

**Comment by Sven65** [comment]
Fixed.
