### ISSUE TITLE
Can't see other players in player list if not the host

### ISSUE THREAD

**Issue by lifeofchrome** [Sven65/TriviaPartyBugs#4]
**Describe the bug**
When joining someone else's game with their code, I am unable to see their player avatar/name in the player list at the top.

**To Reproduce**
1. Join an already-created game
2. Look at the top for other players

**Expected behavior**
All players should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/8226943/42288466-6bcbc280-7f80-11e8-9e9e-8740e3636a57.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome 67.0.3396.99
 - TriviaParty Version: 0.2.3

**Comment by Sven65** [comment]
Fixed.
